name: Post to dev.to site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: posts
        name: Detecting posts from the changes
        run: |
          i=0
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with ${changed_file}."
            if [[ "${changed_file}" == *.md ]];
            then
              echo "File ${changed_file} matched post."
              echo "::set-output name=post${i}::${changed_file}"
              ((i=i+1))
            fi
          done
      - id: checkout
        name: Checkout the repository
        uses: actions/checkout@v2
      - if: steps.posts.outputs.post0
        name: Publish to dev.to
          # You may pin to the exact commit or the version.
          # uses: sinedied/publish-devto@30728bf375a0d24f91e18ae83ecdd219e5ac1878
        uses: sinedied/publish-devto@v1
        with:
          # Your dev.to personal API key to publish and update articles
          devto_key: ${{ secrets.DEVTO_ACCESS_TOKEN }}
          # Your GitHub access token to update files with ID once published
          github_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          # One or more glob patterns of files to include
          files: ${{ steps.posts.outputs.post0 }}
